WORLD_WIDTH = 100
WORLD_HEIGHT = 100

VIEW_WIDTH = 12
VIEW_HEIGHT = 20
VIEW_OFFSET = (40, 40)
HEX_RADIUS = 30

CAMERA_COLUMN = int(VIEW_WIDTH / 2)
CAMERA_ROW = int(VIEW_HEIGHT / 2)

WINDOW_WIDTH = 600
WINDOW_HEIGHT = 700

INVENTORY_WIDTH = 8
INVENTORY_HEIGHT = 8
INVENTORY_CELL_SIZE = 64
